name: Pipeline

on:
  pull_request:
    branches-ignore:
    - 'main'
    - 'alpha'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        always-auth: true
    - uses: actions/checkout@v2
    - name: install
      run: yarn install
    - name: linter
      run: yarn lint
    - name: build
      run: yarn build
